#!/bin/bash
# Launch Hantek 6000BD software in Docker
# Install: sudo cp this-file /usr/local/bin/hantek && sudo chmod +x /usr/local/bin/hantek

exec docker run --rm \
    -p 6080:6080 \
    -v /dev/bus/usb:/dev/bus/usb \
    --device-cgroup-rule='c 189:* rmw' \
    -v /sys/bus/usb:/sys/bus/usb:ro \
    -v /sys/devices:/sys/devices:ro \
    hantek-6000bd
