[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:xvfb]
command=Xvfb :1 -screen 0 2560x1600x24 -ac
autorestart=true
priority=10

[program:fluxbox]
command=fluxbox
environment=DISPLAY=":1"
autorestart=true
priority=20
startsecs=1

[program:x11vnc]
command=x11vnc -display :1 -nopw -forever -shared -rfbport 5900 -noxdamage
autorestart=true
priority=30
startsecs=2

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5900
autorestart=true
priority=40
startsecs=3

[program:hantek]
command=/hantek/start-scope.sh
environment=DISPLAY=":1",WINEPREFIX="/root/.wine",WINEARCH="win64",WINEDEBUG="warn+ntoskrnl,warn+usb"
autorestart=false
priority=50
startsecs=4
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
