[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:xvfb]
command=Xvfb :1 -screen 0 1280x800x24 -ac
autorestart=true
priority=10

[program:fluxbox]
command=fluxbox
environment=DISPLAY=":1"
autorestart=true
priority=20
startsecs=3

[program:x11vnc]
command=x11vnc -display :1 -nopw -forever -shared -rfbport 5900 -noxdamage
autorestart=true
priority=30
startsecs=5

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5900
autorestart=true
priority=40
startsecs=8

[program:hantek]
command=wine "C:\\Program Files\\Hantek6000\\Scope.exe"
environment=DISPLAY=":1",WINEPREFIX="/root/.wine",WINEARCH="win32"
autorestart=false
priority=50
startsecs=12
